### ISSUE TITLE
Support for Javadoc tags

### ISSUE THREAD

**Issue by bolerio** [mulesoft/raml-for-jax-rs#101]
It doesn't seem like the JAX-RS->RAML processor is processing the standard Javadoc comments, including the description of a method, the @param and @return tags. Any plans to support those? That's where the documentation of the API really is so it's not so valuable to have a list of available URIs without a human readable description of what they represent. Thanks!

**Comment by KonstantinSviridov** [comment]
Hi, @bolerio 

Yes, we are planning to support them in all plugins, and the  Eclipse plugin is alredy capable of processing the.

Regards, Konstantin

**Comment by bolerio** [comment]
Ah, yes, it does work from Eclipse, that's great, thanks much for the tip!
