### ISSUE TITLE
release the next version

### ISSUE THREAD

**Issue by RaphC** [mulesoft/raml-for-jax-rs#106]
Hi,

When do you release the next version?

Regards

**Comment by KonstantinSviridov** [comment]
Hi, @RaphC 

We still have some bugs to fix. After we have finished with them, a new version will be released. We think, it will happen in two weeks.

Regards, Konstantin

**Comment by RaphC** [comment]
Thanks Konstantin,

How can we contribute to the project ?

Regards

**Comment by KonstantinSviridov** [comment]
First, you can propose new features, implement them and create pull requests.

Second, you can fix existing bugs and update documentation. (I do not consider this option interesting for people outside the team, but anyway)

In both cases we ask you to sign the contributors agreement:
https://github.com/mulesoft/raml-for-jax-rs#contributing

Regards, Konstantin

**Comment by RaphC** [comment]
Hi Konstantin,
Is the future release planned ?
Regards
