### ISSUE TITLE
We need to support getting descriptions from java doc (when generating raml from java)in our maven plugin

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [mulesoft/raml-for-jax-rs#108]
Original user request:
http://forums.raml.org/t/jax-rs-to-raml-and-javadoc/912

**Comment by nadirloutfi** [comment]
thank you for your reactivity

**Comment by KonstantinSviridov** [comment]
Complete

**Comment by KonstantinSviridov** [comment]
@nadirloutfi 
You are wellcome.
Enhancements are in the 1.3.4-SNAPSHOT

Regards,
Konstantin
