### ISSUE TITLE
Eclipse update site is broken

### ISSUE THREAD

**Issue by InfoSec812** [mulesoft/raml-for-jax-rs#11]
I cannot install the Eclipse plugin from the URL listed on the README

**Comment by MightyMel** [comment]
Same exact issue here. Eclipse can't find anything in both
http://raml-tools.mulesoft.com/raml-for-jax-rs/eclipse
http://raml-tools-stage.mulesoft.com.s3.amazonaws.com/raml-for-jax-rs/current/

and they both return error if I try to access them from a browser.
Also this links says 404 in the same way:
http://raml-tools.mulesoft.com/jaxrs-to-raml/eclipse/site.xml
http://raml-tools-stage.mulesoft.com.s3.amazonaws.com/raml-for-jax-rs/current/site.xml

this is wat I get with the last one, just to clarify:

    <Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    <Key>raml-for-jax-rs/current/site.xml</Key>
    <RequestId>340C74689107E18B</RequestId>
    <HostId>
    GYCVwQAXXksZYuhiGjGLGJqiEZwQymP+DErwrVOFoEczmF95SRyFvjoby/LzPg1tBWafY1MqkDk=
    </HostId>
    </Error>

**Comment by petrochenko-pavel-a** [comment]
Ups, I am very sorry correct url is
http://raml-tools-stage.mulesoft.com.s3.amazonaws.com/raml-for-jax-rs/current/eclipse

**Comment by Graham42** [comment]
I am also having the same problem with the update site. 
Url: http://raml-tools.mulesoft.com/raml-for-jax-rs/eclipse
Eclipse version 4.3.2 (Kepler)
Adding the site to Ecilpse says "No software site found at http://raml-tools.mulesoft.com/raml-for-jax-rs/eclipse"
Trying the url in the browser gives me 
```
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: raml-for-jax-rs/eclipse
RequestId: 8ADF498852A9F6CC
HostId: GyKufDa893JPQ3MQXO7jKkVCRUmeKWlqvyPA6Bb7wOTz0y2YlPLVOdpTgepGKcB8
```

**Comment by vijaykrajpoot** [comment]
I am getting below error while installing it in STS,

An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.apache.commons.io,2.2.0.v201405211200
