### ISSUE TITLE
Extracting parent resource description from class level Javadoc

### ISSUE THREAD

**Issue by bolerio** [mulesoft/raml-for-jax-rs#112]
In RAML, one can document a parent resource like this:

parent:
  description: Description of parent
  /child: 
    get:
      description: Description of /parent/child

etc..

With JAX-RS, the structure is often represented as
```
/**
 * Description of parent
 */
@Path("/parent")
public class MyService
{
 /**
  *  Description of /parent/child
 */
   @GET
   @Path("/child")
   public ...
}
```
Currently raml-for-jax-rs seems to ignore the class level Javadoc which could be used to fill in the parent description. Are there any plans to implement such an option?

**Comment by KonstantinSviridov** [comment]
Thanks, @bolerio. It sounds reasonable.

A Java class defines a tree of resources. It's natural to pass it's description to the root of the tree. And in case when several classes in our input define trees with common root we will sum up their descriptions.

Regards, Konstantin.

**Comment by bolerio** [comment]
Thanks, that'll be great!

**Comment by KonstantinSviridov** [comment]
Hi, @bolerio 

Just finished implementing passing class comments into resource descriptions.

Regards,
Konstantin

**Comment by bolerio** [comment]
That’s great, and fast! Thanks so much :)
