### ISSUE TITLE
Perform eclipse plugin work as a background task

### ISSUE THREAD

**Issue by n4zukker** [mulesoft/raml-for-jax-rs#115]
The eclipse plugin currently executes all its work in a blocking manner when the Ok button is hit.  This locks up the GUI while the generation is in process.

As a user, I would like for the plugin to do its work in the background and show progress in the Progress view.  It takes about twenty seconds for RAML files to be created and right now for that time, Eclipse becomes unresponsive.  Background work would let me watch the process, even showing detailed progress messages, and let me cancel that work or continue to do development in the meantime.

**Comment by KonstantinSviridov** [comment]
Thanks for another important issue.

Now it should be fine.
