### ISSUE TITLE
Annotation inheritance

### ISSUE THREAD

**Issue by tramasoli** [mulesoft/raml-for-jax-rs#116]
Hello! Supose I have:
```java
abstract class Base {
   @GET
   @Path("foo")
   Response getContents();
}

@Path("concretews")
class Concrete extends Base {
   @GET
   @Path("newmethod")
   Response getAnotherContent() { return Response...build().... ; }
}
```
The generated RAML code ignores everything annotaded on Base class. Shouldn't it consider it too?

Thanks in advance for the help.

**Comment by ddossot** [comment]
I'm in favour of having the JAX-RS->RAML plugin follow the JAX-RS specs as far as inheritance is concerned:

> ## 3.6 Annotation Inheritance
> JAX-RS annotations may be used on the methods and method parameters of a super-class or an implemented interface. Such annotations are inherited by a corresponding sub-class or implementation class method provided that the method and its parameters do not have any JAX-RS annotations of their own. Annotations on a super-class take precedence over those on an implemented interface. The precedence over conflicting annotations defined in multiple implemented interfaces is implementation specific. Note that inheritance of class or interface annotations is not supported.
> If a subclass or implementation method has any JAX-RS annotations then all of the annotations on the superclass or interface method are ignored.

So in your case, because `Concrete` is JAX-RS annotated, all annotations from `Base` should be ignored.

**Comment by tramasoli** [comment]
Thank you, David. I'm just beginning with jaxrs and don't know the refs.
But, since I'm using jersey, I thought the behavior wasn't as expected. ;)
I will modify my code to explicitly call the super methods then to follow
the refs.

Thanks again.
Em 01/07/2015 11:31, "David Dossot" <notifications@github.com> escreveu:

**Comment by tramasoli** [comment]
Wait, I've read the documentation (http://download.oracle.com/otn-pub/jcp/jaxrs-2_0-fr-eval-spec/jsr339-jaxrs-2.0-final-spec.pdf?AuthParam=1435786627_d0b0fe164da1b3f676012f42a97d6c07) and the example shows that I'm right. My class (as the example above) has annotations, but I'm not overriding the method "getContents();" from the superclass neither am I changing it's annotations. 
Example:
```java
@GET @Produces("application/atom+xml")
   Feed getFeed();
}
@Path("feed")
public class ActivityLog implements ReadOnlyAtomFeed {
   public Feed getFeed() {...}
}
```
Quote:
> In the above, ActivityLog.getFeed inherits the @GET and @Produces annotations from the interface.

So I guess my issue is relevant.

**Comment by ddossot** [comment]
You're right, sorry. I read too fast and thought the method was overridden :sob:

**Comment by tramasoli** [comment]
No problem, I must thank you for poinying the docs and the right path to look for my issue, as I stated before I'm a begginer with jaxrs (and jee) and any info is appreciated.
Maybe I'll look how to solve and propose a patch if another one don't do it first.

**Comment by KonstantinSviridov** [comment]
Hi @ddossot and @tramasoli 

I'm going to switch to this issue now.

**Comment by tramasoli** [comment]
Thank you so much!

**Comment by KonstantinSviridov** [comment]
Hi all,
I've implemented inheritance support fo JAX RS resources and JAXB model classes.
