### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by grbush** [mulesoft/raml-for-jax-rs#127]
Hi, 

We are very interested in using this tool for documenting our API. However some bugs are making it a bit difficult. 

There was a Null Pointer Exception in APTResourceVisitor introduced in this commit: https://github.com/mulesoft/raml-for-jax-rs/commit/b89a48417ff5147badef4e28ef11e4cbec25278b

The variable "name" is guaranteed to be null here: `String name = t.getFullyQualifiedName();`

 because APTType contains this code:

	public String getFullyQualifiedName() {
		return null; //Can't get it without utils
	}

However next line name is used without a null pointer check

`if(name.equals("void")||name.equals("java.lang.Void")){
			return false;
		}`

I suggest changing it to:

`if(name == null || name.equals("void")||name.equals("java.lang.Void")){
			return false;
		}`

Cheers,
Geoff.

**Comment by KonstantinSviridov** [comment]
Hi, Geoff

I have commited fix for the NPE, but there is still much to be fixed in the Javac plugin. Right now Maven plugin is much better tested.

Regards, Konstantin.

**Comment by grbush** [comment]
Thanks very much, I will try out the Maven plugin. Our java codebase is stuck on an ant-based build system :( 

Will let you know how it goes.
