### ISSUE TITLE
Error generating raml from jaxrs

### ISSUE THREAD

**Issue by rahullao** [mulesoft/raml-for-jax-rs#140]
Hi,

I have written web services of my Java project using resteasy. For the documentation process i want these web services to be captured using RAML.

For this i followed - https://github.com/mulesoft/raml-for-jax-rs and https://github.com/mulesoft/raml-for-jax-rs/blob/master/maven-plugin.md

In the second link i started the steps for JAX-RS to RAML and followed all the steps.

Instead of using the version 0.0.1-SNAPSHOT or 1.3.4-SNAPSHOT i am using 1.3.3, as i was getting an error when using the first two version. Error is described below
Error -
Failed to read artifact descriptor for org.raml.plugins:jaxrs-raml-maven-plugin:jar:1.3.4-SNAPSHOT: Could not find artifact org.raml:jaxrs-to-raml:pom:1.3.4-SNAPSHOT in Nexus-One (mvn-repo/nexus/content/groups/One) -> [Help 1]

So now using 1.3.3 resolved the above but i am getting another error of **NoSuchMethodError.**
Error Details are - 
[ERROR] Failed to execute goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3:generate-raml (default) on project spectralight: Execution default of goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3:generate-raml failed: An API incompatibility was encountered while executing org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3:generate-raml: java.lang.NoSuchMethodError: com.mulesoft.jaxrs.raml.annotation.model.IParameterModel.getType()Ljava/lang/String;

So i went to check the class file of IParameterModel in com.mulesoft.jaxrs.raml.annotation.model package and it turns out that this interface does not have the method.

I have also attached the complete error log while doing mvn package for my project.
![errorlogpart1](https://cloud.githubusercontent.com/assets/8056001/10534154/c2ec75a2-73f1-11e5-85c5-e13d50d1daed.JPG)
![errorlogpart2](https://cloud.githubusercontent.com/assets/8056001/10534153/c24dad96-73f1-11e5-95cf-1714303c7806.JPG)

Please can anyone specify how to resolve this error and generate raml files for my webservices.

**Comment by ddossot** [comment]
It's really weird that it still tries to fetch `1.3.4-SNAPSHOT`. Do you mind sharing your pom.xml?

**Comment by rahullao** [comment]
Could not share the whole pom but sharing parts related to raml changes. I hope that would be fine.
![pomchangesforraml1 1](https://cloud.githubusercontent.com/assets/8056001/10576973/0ca01e5c-7685-11e5-9ebf-5a7ff3f1d5bc.JPG)
![pomchangesforraml1 2](https://cloud.githubusercontent.com/assets/8056001/10576975/0ca6649c-7685-11e5-8361-3ee6785d9ff5.JPG)
![pomchangesforraml1 3](https://cloud.githubusercontent.com/assets/8056001/10576974/0ca1f2a4-7685-11e5-9e45-94d72b5d5e7d.JPG)

**Comment by ddossot** [comment]
Replace:

    <versionRange>1.3.3</versionRange>

with:

    <version>1.3.3</version>

That should fix the issue.

**Comment by rahullao** [comment]
Thanks David, this resolves the issue.
One thing to be taken care is that we would also need to delete previous versions from maven repository. Not deleting them it might still try to fetch 1.3.4-SNAPSHOT.
