### ISSUE TITLE
JAX-RS to RAML via command line issue

### ISSUE THREAD

**Issue by Pranav794** [mulesoft/raml-for-jax-rs#143]
Here's my situation:

I've tried the Eclipse plugin to generate my RAML files. Works flawlessly which is great.
I want to do this via command line.
I followed the instructions on the doc. I've downloaded the jax-rs-to-raml.jar. which is apparently all I need to use the tool. The problem is it cannot find the -processor :
'com.mulesoft.jaxrs.raml.annotation.model.apt.RAMLAnnotationProcessor'
In the instructions, it tells us to use this processor. 

NOTE: I've also tried installing it via mvn. Using these steps:

- Go to the `com.mulesoft.jaxrs.raml.generator` folder.
- Run `mvn clean package install`
- Go to the `com.mulesoft.jaxrs.raml.generator.annotations/target` folder where you will find the generated jar

After running mvn clean package install, build is successful however, there's no target folder in  com.mulesoft.jaxrs.raml.generator.annotations.

Feedback is welcome.

**Comment by alexanderosipov** [comment]
Please execute `mvn clean assembly:assembly -DdescriptorId=jar-with-dependencies`
This will create jaxrs-to-raml/com.mulesoft.jaxrs.raml.generator.annotations
