### ISSUE TITLE
When release 1.3.4 

### ISSUE THREAD

**Issue by sveba** [mulesoft/raml-for-jax-rs#152]
Hi,

i just wanted to ask if there is a timeline when 1.3.4 release can be found in the official repo?

Thank you for the great work!

**Comment by RaphC** [comment]
+1

**Comment by donduni** [comment]
+1

**Comment by petrochenko-pavel-a** [comment]
Hy guys, we are very sorry about enormous delays with releases we promise to do a release on the next week. 

Thanks for you patience, and very sorry.

Best regards,
Pavel

**Comment by RaphC** [comment]
Thank you,

I'm looking forward the next week !!! :)

**Comment by RaphC** [comment]
Hi Pavel,

When do you plan to release ?

Regards

**Comment by jeroenver** [comment]
I cannot see a release done here in github but I did found for example http://mvnrepository.com/artifact/org.raml.plugins/raml-jaxrs-maven-plugin/1.3.4

So is it released but simply not tagged?

Thanks, Jeroen

**Comment by RaphC** [comment]
curious, the pom files on the trunk are still in 1.3.4-SNAPSOT ...

**Comment by alexanderosipov** [comment]
Hi guys, sorry for delay, release is published, you are welcome )

**Comment by RaphC** [comment]
thanks for your great work.
