### ISSUE TITLE
Update version of jsonschema2pojo to 0.4.17

### ISSUE THREAD

**Issue by blizznets** [mulesoft/raml-for-jax-rs#155]
I use raml plugin with jsonschema2pojo for generating request response classes.
I'm waiting for fixes in jsonschema2pojo.

Do you plan to update version of jsonschema2pojo ?

**Comment by joshi-hitesh** [comment]
Which version of Jsonschema2Pojo is being used right now.
If I have json spec 4 and try to generate JSR 303 annotated POJO's . It does not generate @NotNull annotation for the required fields.
I tried generating a POJO with such a JSON in jsoschema2pojo.org and it generates the POJO correctly.

**Comment by alexanderosipov** [comment]
updated to 0.4.20
