### ISSUE TITLE
Intentional use of "s" suffix from schema for generated class

### ISSUE THREAD

**Issue by benlei-neustar** [mulesoft/raml-for-jax-rs#190]
If I have a car, and a list of cars, I would like the ability to have the generated Cars class to be named "Cars" and not "Car_". Is there a way to allow this behavior?

**Comment by jeroenver** [comment]
You can specify your own javaType in the schema. The underlying schema2pojo library will use that class name instead of generating its own: https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#javatype
