### ISSUE TITLE
Codegen for RAML 1.0 spec

### ISSUE THREAD

**Issue by vijayrcse** [mulesoft/raml-for-jax-rs#197]
Hi Team
I am using RAML 1.0 spec and plugin version is 1.3.5-snapshot. could you please advise 1.0 spec is support in this version?
Thanks 
-Vijay

**Comment by petrochenko-pavel-a** [comment]
Hi Vijay,
unfortunately there is no support for RAML 1.0 yet. (see #150 )

Regards,
Pavel

**Comment by vijayrcse** [comment]
thanks Pavel
