### ISSUE TITLE
problem with code compilation

### ISSUE THREAD

**Issue by lautarobock** [mulesoft/raml-for-jax-rs#22]
when mvn compile

`Albums.java:[5,18] error: package javax.ws.rs does not exist`

**Comment by KonstantinSviridov** [comment]
Hi, @lautarobock 

As I see, the generated project does not have a `javax.ws.rs` among its dependencies. Now the generator does not attempt to manage dependencies leaving them for the user. For example, you may use these dependencies:
https://github.com/mulesoft/raml-for-jax-rs/blob/master/jaxrs-to-raml/examples/helloworld/pom.xml#L49-65

Regards, Konstantin
