### ISSUE TITLE
jaxrs-to-raml examples aren't correctly set up for jaxrs-raml-maven-plugin

### ISSUE THREAD

**Issue by shane-axiom** [mulesoft/raml-for-jax-rs#27]
It seems like the content in jaxrs-to-raml/examples is stale. Only one of these projects is actually configured to use the jaxrs-raml-maven-plugin (contacts), and it's pointing to an 0.0.1-SNAPSHOT version of the plugin instead of the current version (1.3.2-SNAPSHOT). None of the other example project poms are configured to use jaxrs-raml-maven-plugin.

In addition, jaxrs-raml-maven-plugin in contacts' pom.xml is configured to run during `generate-sources`, at a time when the needed target/classes directory doesn't exist. This should be changed to `process-classes` or later.

Shouldn't some of these example projects be configured to use jaxrs-raml-maven-plugin?

**Comment by bikegriffith** [comment]
+1

**Comment by petrochenko-pavel-a** [comment]
Hi, guys, hopefully we will have a bit of time to  work on improving examples  on next week

**Comment by KonstantinSviridov** [comment]
Finally fixed it.
