### ISSUE TITLE
Can't install in Mulesoft Studio

### ISSUE THREAD

**Issue by jorgegarciamule** [mulesoft/raml-for-jax-rs#30]
I get this error:

![screen shot 2015-01-09 at 11 24 56 am](https://cloud.githubusercontent.com/assets/7658927/5680944/47dcaae8-97f2-11e4-92bc-e9a0a428cadc.png)

Using:

Anypoint Studio October 2014 Release
Version: 4.1.1
Build Id: 201411041003

**Comment by KonstantinSviridov** [comment]
Before installing the RAML plugin, try installing `SLF4J` from the http://logback.qos.ch/p2 update site.

**Comment by jorgegarciamule** [comment]
It works! Thanks for the fast response!

--------------------------------

*Jorge L GARCIA PEREZ*

Solutions Engineer - Global SE Team
MuleSoft Inc.
