### ISSUE TITLE
gradle support

### ISSUE THREAD

**Issue by billumina** [mulesoft/raml-for-jax-rs#32]
When will the "coming soon" for gradle be available?

Where is the code for gradle?

**Comment by petrochenko-pavel-a** [comment]
Hi billumina,

There is some pretty nicely done gradle support at 

https://github.com/jdpgrailsdev/raml-jaxrs-codegen/tree/master/gradle-plugin

Unfortunately this guy did not signed Mulesoft Contributor Agreement(https://api-notebook.anypoint.mulesoft.com/notebooks#bc1cf75a0284268407e4) so I can not integrate his code yet. I will try to ping him again today

Regards,
Pavel

**Comment by billumina** [comment]
Thanks
