### ISSUE TITLE
When will a release build be available?

### ISSUE THREAD

**Issue by ddossot** [mulesoft/raml-for-jax-rs#37]
Issue #23 has been wrongfully closed. I can't re-open it so I submit this new issue.

From my latest comment in #23:

----

This ticket is about releasing the plugins, not just snapshot builds.

At this point, there's still no release of these plugins in the MuleSoft public releases repo: https://repository.mulesoft.org/nexus/content/repositories/releases/org/raml/

Without official releases from MuleSoft, everyone is forced to build their own non-snapshot releases in order to be able to release their own projects which depend on these plugins.

The current version is `1.3.2-SNAPSHOT`, suggesting that many releases have occurred but where are they? Could you release `1.3.2`?

**Comment by ddossot** [comment]
@usarid Could potentially chime in on this?

**Comment by petrochenko-pavel-a** [comment]
yep, you might just reopen it.

**Comment by ddossot** [comment]
I can't, the option is not available.
