### ISSUE TITLE
Eclipse plugin does not install

### ISSUE THREAD

**Issue by Graham42** [mulesoft/raml-for-jax-rs#39]
Eclipse version 4.3.2 (Kepler)
Using update site: https://s3.amazonaws.com/raml-tools-stage.mulesoft.com/raml-for-jax-rs/current/eclipse 
When trying to install the eclipse plugin it fails with these details 
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: RAML for JAX-RS 1.3.2.201501161519 (com.mulesoft.jaxrs.raml.feature.feature.group 1.3.2.201501161519)
  Missing requirement: Generator 1.3.2.201501161519 (com.mulesoft.jaxrs.raml.generator 1.3.2.201501161519) requires 'package org.apache.commons.beanutils 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: RAML for JAX-RS 1.3.2.201501161519 (com.mulesoft.jaxrs.raml.feature.feature.group 1.3.2.201501161519)
    To: com.mulesoft.jaxrs.raml.generator [1.3.2.201501161519]
```

**Comment by petrochenko-pavel-a** [comment]
Hi Graham,  thanks a lot for filing this I will try to deal with this asap. 

Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment]
Hi Graham I have tried to reproduce issue with fresh new Kepler Service Release 2
Build id: 20140224-0627

And it worked fine.

In case if 'Contact all update side options during install to find required software' was turned off it showed remediation page which allows to update installation to be compatible.

If this option is turned on it just installed feature without any problems.

Please let me know if you are not able to install with fresh Kepler as well 
what build Id of Kepler are you using.

Thanks in advance,
Pavel

**Comment by Graham42** [comment]
I ended updating my version of eclipse (to Luna) and the plugin installed fine.
