### ISSUE TITLE
Forgot to push to GitHub?

### ISSUE THREAD

**Issue by ddossot** [mulesoft/raml-for-jax-rs#40]
Version `1.3.2` has been released but:

- the POMs in GitHub are still on `1.3.2-SNAPSHOT`,
- there's no tag for the `1.3.2` version.

So it seems pushing to git has been missed, after the release.

**Comment by petrochenko-pavel-a** [comment]
Actually I do not forgot, but what is still not clear to me is what release policy to choose, what I am going to is to create separate branches for each release, and move to 1.3.3-SNAPSHOT in master.

Sounds ok?
Regards,
Pavel

**Comment by ddossot** [comment]
Tagging is enough, you can always create a branch later if you want to do a maintenance release for a previous version. For this project I suspect this will not happen.

I guess you're not using the Maven release plugin, otherwise this would be done automatically.

And I still think something hasn't been pushed because the POMs are still on `1.3.2-SNAPSHOT`, which is wrong by any standard, whether you use the Maven release plugin or not. Once a release has been made, the POM versions should be set to a snapshot of the next release version.

**Comment by petrochenko-pavel-a** [comment]
Yep I can not because it will not set versions for eclipse related artefacts correctly, moving versions forward

**Comment by ddossot** [comment]
IMO there is something deeply broken here, and this is a first in MuleSoft's open source history :cry:

**Comment by petrochenko-pavel-a** [comment]
Done
