### ISSUE TITLE
Tag 1.3.2 is on wrong commit

### ISSUE THREAD

**Issue by ddossot** [mulesoft/raml-for-jax-rs#41]
Tag 1.3.2 is on commit c47cecb, dated October 24th 2014.

I should be on commit 038a29d instead.

**Comment by petrochenko-pavel-a** [comment]
Hm strange how eclipse tagged it. moved tag forward

**Comment by ddossot** [comment]
Cool, yeah, don't trust Eclipse for any SCM operation. The command line is your true friend here.
