### ISSUE TITLE
RAML to Jax-RS not supporting date type

### ISSUE THREAD

**Issue by ymcnicoll** [mulesoft/raml-for-jax-rs#45]
I'm using raml-for-jax-rs latest release to generate Jersey skeleton. Everything worked fine until this afternoon. Maven plugins stopped recognising date type and I have (notice the "null" between the integer and number) the following error:

error: "date" is not a valid primitive type (valid values are: [array, boolean, integer, null, number, object, string])
[ERROR] level: "error"
[ERROR] domain: "syntax"
[ERROR] schema: {"loadingURI":"#","pointer":"/properties/endDate"}
[ERROR] keyword: "type"
[ERROR] found: "date"
[ERROR] valid: ["array","boolean","integer","null","number","object","string"]

Anyone else having this error !!!

**Comment by petrochenko-pavel-a** [comment]
Hm, sounds pretty weird. Testing

**Comment by ddossot** [comment]
@ymcnicoll What version of the plugin are you using?

**Comment by ymcnicoll** [comment]
When it first started to happen I was using 1.3.2. At that point I was wondering if part of the plugins or one of its dependencies got updated without I noticed.

 

So I downloaded the lastest snapshot from the site 1.3.3 and build-it locally (without errors) and I got the same result.

 

Yan McNicoll

 

De : David Dossot [mailto:notifications@github.com] 
Envoyé : 6 mars 2015 10:00
À : mulesoft/raml-for-jax-rs
Cc : ymcnicoll
Objet : Re: [raml-for-jax-rs] RAML to Jax-RS not supporting date type (#45)

 

@ymcnicoll <https://github.com/ymcnicoll>  What version of the plugin are you using?

**Comment by petrochenko-pavel-a** [comment]
Hi it is actually the result of RAML parser improvements which validates JSON schemas now. See (http://tools.ietf.org/html/draft-zyp-json-schema-04#section-3.5). 

Current schema generator should never emit this type in json schema definition. 


Regards,
Pavel
