### ISSUE TITLE
jax-rs->raml : Media type mapping with single value

### ISSUE THREAD

**Issue by Kindrat** [mulesoft/raml-for-jax-rs#48]
Is it possible to use single value mappings instead of arrays?
working:
   @Produces({MediaType.APPLICATION_JSON})
   @Consumes({MediaType.APPLICATION_JSON})
not working:
   @Produces(MediaType.APPLICATION_JSON)
   @Consumes(MediaType.APPLICATION_JSON)

**Comment by petrochenko-pavel-a** [comment]
Yes it works fine for me. In plain case at least (just tested it on swagger example) May you please send me a bit more detailed example of configuration which does not work for you. And I will try to fix it asap.

Thanks in advance,
Pavel

**Comment by Kindrat** [comment]
https://www.dropbox.com/s/fbd5tj1nblq5g3v/RamlDemoMediaType.zip?dl=0

Generated raml:
```
#%RAML 0.8
title: api docs
version: 1.0-SNAPSHOT
baseUri: "http://localhost:8080/"
schemas:
  - profile: !include schemas/profile.xsd
  - profile-jsonschema: !include schemas/profile-jsonschema.json
/profiles/customer: 
  post: 
    responses: 
      200: 
  put: 
    body: 
      application/json: 
        schema: profile-jsonschema
        example: !include examples/profile.json
    responses: 
      200: 
        body: 
          application/json: 
```
As you see, post endpoint does not contain mediatype and examples, put endpoint contains them.

**Comment by Kindrat** [comment]
Also, swagger example uses array value
```
@Path("/{snt}")
@Produces({ "application/json" })
@GET
```

**Comment by petrochenko-pavel-a** [comment]
I figured the difference it worked in JDT based environment and do not worked in Spoon,fixed
