### ISSUE TITLE
Misleading project description

### ISSUE THREAD

**Issue by fkirill** [mulesoft/raml-for-jax-rs#49]
He guys, you must have forgot to change the project description that now reads as "Starting from JAX-RS-annotated Java code, generate a RAML API description" and is in contradiction with the text that follows below. It should be something like "two-way generation" or such.

**Comment by petrochenko-pavel-a** [comment]
Hi @fkirill thanks a lot for your finding, I changed project description a bit. Please let me know if you have a better idea for headline.

Thanks in advance,
Pavel
