### ISSUE TITLE
The generator does not use Response for the Schema or Example generation

### ISSUE THREAD

**Issue by vebhhav** [mulesoft/raml-for-jax-rs#51]
Two issues faced by Cisco in JAX-RS for RAML to generate RAML 
-Swagger Annotations @APIResponse takes a parameter for code, message and response. The generator does not use Response for the Schema or Example generation;

**Comment by petrochenko-pavel-a** [comment]
Hi @vebhhav, thanks a lot for filing this , yes we are currently having very limited support for swagger annotations and it is a definitely point for improvement. There are some discussions about how it should be bundled but in general we will try to support it asap.
Regards,
Pavel

**Comment by vebhhav** [comment]
Thanks.

How can we help you to get this fixed.

Regards
-veb

**Comment by usarid** [comment]
As with the other issue, please clarify: this isn't a bug that needs
fixing, this is extra functionality to add to this project, yes?

**Comment by petrochenko-pavel-a** [comment]
Hi @vebhhav,  I am going to work on adding this functionality into the project. Do you have any examples of use-cases that I may use for testing of this feature. (I already have couple in my mind, but it would be nice to be sure that we are on same plate). I am mostly interested in your vision of how it should behave in the cases when we have code annotated both with jax-rs and swagger annotations.

Thanks in advance,
Pavel

**Comment by KonstantinSviridov** [comment]
fixed at 1.3.4-SNAPSHOT
