### ISSUE TITLE
raml->jax-rs: Upgrade jsonschema2pojo to 0.4.10

### ISSUE THREAD

**Issue by ddossot** [mulesoft/raml-for-jax-rs#53]
The generator is now 5 releases behind the current version of jsonschema2pojo. Since it's a library providing a core feature, it would be nice not to fall behind too much in term of versions.

**Comment by petrochenko-pavel-a** [comment]
Agree, will test newest release and integrate them. (sorry for long response was in flight from BA)

Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment]
done
