### ISSUE TITLE
raml-jaxrs maven plugin references raml-parser snapshot not in central maven

### ISSUE THREAD

**Issue by northlander** [mulesoft/raml-for-jax-rs#54]
When using raml-jaxrs-maven-plugin 1.3.3 (from central maven site), it requires/tries to download org.raml:raml-parser:jar:0.9-20150218.154027-76 which does not exist in central maven. 

Is this intended?

Usage:
<plugin>
                <groupId>org.raml.plugins</groupId>
                <artifactId>raml-jaxrs-maven-plugin</artifactId>
                <version>1.3.3</version>
                <configuration>

**Comment by ddossot** [comment]
That can't be intended, no. Everything should be in central for this to work. Moreover the dependency on a snapshot is fragile and may eventually break if the Nexus server where this snapshot is deployed starts culling old artifacts.

It turns out the RAML Java parser artifacts are not deployed to central: https://github.com/raml-org/raml-java-parser/blob/master/pom.xml#L209-L220 That must be addressed first.

Then they should also release an 0.9-RC1 to central so the raml-jaxrs-maven-plugin will have a stable version to rely on.

**Comment by petrochenko-pavel-a** [comment]
https://github.com/raml-org/raml-java-parser/issues/59 Filed.

**Comment by northlander** [comment]
Is there any reason to use 0.9-SNAPSHOT at all? Seems there has been no real commits to raml-java-parser since the 0.8.11 release. For all I can understand, using 0.8.11 (given that is pushed to maven central) would do it.

from https://github.com/raml-org/raml-java-parser/releases/tag/0.8.11
> 0.8.11
> @svacas svacas tagged this on 18 Feb · 1 commit to master since this tag

**Comment by ddossot** [comment]
@northlander No idea for 0.9 versus 0.8, @petrochenko-pavel-a may know.

Where do you see raml-java-parser in central? http://search.maven.org/#search|ga|1|raml-java-parser

**Comment by petrochenko-pavel-a** [comment]
@northlander actually it is there are at least several import fixes (one that is most important for me is relative includes support)

**Comment by northlander** [comment]
Sorry, missed the pull requests on raml-java-parser 0.9, my bad.

@ddossot No, I did not find it in maven central - I just wrongly assumed the 0.8.11 release would do it (if that release was pushed into maven central) Sorry for any confusion :)

**Comment by robbanw** [comment]
This seems to be resolved now.
https://github.com/raml-org/raml-java-parser/issues/59#issuecomment-96954639

**Comment by northlander** [comment]
Wonderful. So hopefully, the next release of raml-for-jax-rs will use the officially distributed dependencies.

**Comment by ddossot** [comment]
It's not yet available on Central: http://search.maven.org/#search|ga|1|raml-parser I don't think they've promoted the release yet.

**Comment by jeroenver** [comment]
Hi, do you have an ETA on a version 1.3.4 of raml-jaxrs-codegen-core that would use a final version of the raml-parser?
The only way I can get this to work now is by uploading org.raml:raml-parser:jar:0.9-20150218.154027-76 into our artifactory ...

**Comment by magnus-larsson** [comment]
Any update on when you plan to release 1.3.4?
The existing version is missing a lot of critical fixes in 1.3.4-SNAPSHOT and relying on a snapshot version is not a very good practice :-)

**Comment by dmiorandi** [comment]
I'm using nexus. Is not clear to me how can you upload a snapshot version on repository?
So that anyone have a solution to make raml2jaxrs work?

**Comment by lldata** [comment]
+1 for getting 1.3.4 out 

While we wait for that you can force the plugin to use the 8.1.1 parser

	<build>
		<plugins>
			<plugin>
			    <groupId>org.raml.plugins</groupId>
			    <artifactId>raml-jaxrs-maven-plugin</artifactId>
			    <version>1.3.3</version>
			    <configuration>
                                  
			    </configuration>
			    <dependencies>
					<dependency>
						<groupId>org.raml</groupId>
						<artifactId>raml-jaxrs-codegen-core</artifactId>
						<version>1.3.3</version>
						<exclusions>
							<exclusion>
								<groupId>org.raml</groupId>
								<artifactId>raml-parser</artifactId>
							</exclusion>
						</exclusions>
					</dependency>
					<dependency>
						<groupId>org.raml</groupId>
						<artifactId>raml-parser</artifactId>
						<version>0.8.11</version>
					</dependency>
			    </dependencies>

While the above gets maven to move on, I don't know if it makes sense to use that parser version.

Parser 8.1.2 is out but not published (https://github.com/raml-org/raml-java-parser/issues/59)

**Comment by dmiorandi** [comment]
It works. Tks @lldata.

+1 for getting 1.3.4 out, me too.

**Comment by anthonygraignic** [comment]
+1 for getting 1.3.4 out too with non-snapshots dependencies :).

**Comment by giacgbj** [comment]
+1 for getting 1.3.4 out.
