### ISSUE TITLE
Fix no #51 and 52 (@ApiResponse and @Apiresponses) not reflecting via eclipse plugin

### ISSUE THREAD

**Issue by arubalac** [mulesoft/raml-for-jax-rs#57]
Hi 

To check the fix #51 and 52 whihc closed.
I re-installed the ramlforjaxrs eclipse plugin in Anypoint studio and ran it against the my code but I am not able to see the change getting reflected.
I have used the following  url for update site : https://s3.amazonaws.com/raml-tools-stage.mulesoft.com/raml-for-jax-rs/current/eclipse

Could you please let me know is there any change in the url?  Or do i need to follow any other procedure for plugin installation.?

Not sure but think the eclipse update site is not referring the central maven .

Regards
Arun

**Comment by petrochenko-pavel-a** [comment]
Thanks  a lot  for your finding.

Should work fine now

Regards,
Pavel

**Comment by arubalac** [comment]
Thanks a lot Petro for the quick turn around. The fix is working fine.

Regards
Arun
