### ISSUE TITLE
Missing Maven dependency in com.mulesoft.jaxrs.raml.generator

### ISSUE THREAD

**Issue by hindsholm** [mulesoft/raml-for-jax-rs#58]
The pom.xml for com.mulesoft.jaxrs.raml.generator uses an artifact named `jlibs-xml` from the repository https://dl.dropboxusercontent.com/u/326301/repository .

Unfortunately, this repository is no longer available (it gives a 404 error), so I am not able to use com.mulesoft.jaxrs.raml.generator or any of the Maven plugins that depend on this one.

Is there a known workaround for this, or would you perhaps add jlibs-xml to the master repository?

**Comment by petrochenko-pavel-a** [comment]
Hi thanks a lot for finding this, dependency was obsolete so I removed it.

Regards,
Pavel

**Comment by nadirloutfi** [comment]
Hi,
You said this dependency is obsolete but we still need it when we use jaxrs-raml-maven-plugin. How can we manage it ?
