### ISSUE TITLE
!include schema files cant be resolved

### ISSUE THREAD

**Issue by gaalandr** [mulesoft/raml-for-jax-rs#61]
Hi,

I am using raml-for-jax-rs with the mavin plugin to generate code from a RAML spec I have written using the API Designer. My spec has a schema section which !includes schema files located in the same directory as the raml file from which I am generating code.

When I try to compile I keep getting Include cannot be resolved error messages from the generator and I don't see why. Here is an example of the output

[ERROR] ERROR Include cannot be resolved rep.json (line 25, col 10 to 27)

I found the same issue in raml-jaxrs-codegen: https://github.com/mulesoft/raml-jaxrs-codegen/issues/9, what could be related to this. 
Is this fix available in 1.3.3?
				<groupId>org.raml.plugins</groupId>
				<artifactId>raml-jaxrs-maven-plugin</artifactId>
				<version>1.3.3</version>
My raml part:
schemas:
  - reps: !include rep.json

Can you please help me with this?
Thank you
Andrew

**Comment by petrochenko-pavel-a** [comment]
Hi @gaalandr, this issue looks to be related to RAML java parser which we are using, if you will be able to provide your raml file I may try to investigate it and propose patch to RAML parser team.

Thanks in advance,
Pavel

**Comment by gaalandr** [comment]
How can I upload the file?

**Comment by ddossot** [comment]
@gaalandr is the `rep.json` file located in the same directory as the RAML one?

**Comment by gaalandr** [comment]
yes it is in the same directory. (but it was also a problem if it was in a different one)

**Comment by gaalandr** [comment]
#%RAML 0.8
---
title: My Avon Office
version: 1
protocols: [ HTTP, HTTPS ]
mediaType: application/json
schemas:
  - presentation: !include example.json
      
  - presentations: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "description": "A collection of product Presentations",
         "properties": {
           "size":  { "type": "integer", "required": true },
           "presentations":  {
              "type": "array",
              "items": { "$ref": "presentation" }
           }
         }
      }
  - product: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "description": "A single Product",
         "properties": {
           "id":  { "type": "string", "required": true },
           "name":  { "type": "string", "required": true },
           "description":  { "type": "string" },
           "imageUrl":  { "type": "string" },
           "region": { "type": "string", "required": true }
         }
      }
  - products: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "description": "A collection of Products",
         "properties": {
           "size":  { "type": "integer", "required": true },
           "products":  {
              "type": "array",
              "items": { "$ref": "product" }
           }
         }
      }
resourceTypes:
  - base:
      get?:
        responses: &standardResponses
          200:
            description: OK
      put?:
        responses: *standardResponses
      patch?:
        responses: *standardResponses
      post?:
          responses:
            201:
              description: Created
      delete?:
        responses: *standardResponses
  - collection:
      type: base
      get:
        is: [ paged ]
      post:
  - typedCollection:
      type: collection
      get:
        responses:
          200:
            body:
              application/json:
                schema: <<collectionSchema>>
      post:
        body:
          application/json:
            schema: <<schema>>
        responses:
          201:
            body:
              application/json:
                schema: <<schema>>
  - member:
      type: base
      get:
      put:
      patch:
      delete:
  - typedMember:
      type: member
      get:
        responses:
          200:
            body:
              application/json:
                schema: <<schema>>
      put:
        body:
          application/json:
            schema: <<schema>>
        responses:
          200:
            body:
              application/json:
                schema: <<schema>>
      patch:
        body:
          application/json:
            schema: <<schema>>
        responses:
          200:
            body:
              application/json:
                schema: <<schema>>
      delete:
traits:
  - paged:
      displayName: paged
      queryParameters:
        start:
          displayName: start
          description: The first page to return
          type: integer
        pages:
          displayName: pages
          description: The number of pages to return
          type: integer
  - secured:
      displayName: secured
      headers:
        Authorization:
          description: The auth token for this request
      responses:
        401:
          description: Unauthorized
/presentations: &presentations
  type: { typedCollection: { schema: presentation, collectionSchema: presentations } }
  is: [ secured ]
  get:
    queryParameters:
      title:
        type: string
        displayName: title
        description: Filter by title
  /{presentationId}:
    type: { typedMember: { schema: presentation } }
    is: [ secured ]
/products:
  type: { typedCollection: { schema: product, collectionSchema: products } }
  is: [ secured ]
  get:
    queryParameters:
      region:
        type: string
        displayName: region
        description: Filter by region
  /{productId}:
    type: { typedMember: { schema: product } }
    is: [ secured ]
    /presentations: *presentations

**Comment by gaalandr** [comment]
```

#%RAML 0.8
---
title: My Avon Office
version: 1
protocols: [ HTTP, HTTPS ]
mediaType: application/json
schemas:
  - presentation: !include example.json
      
  - presentations: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "description": "A collection of product Presentations",
         "properties": {
           "size":  { "type": "integer", "required": true },
           "presentations":  {
              "type": "array",
              "items": { "$ref": "presentation" }
           }
         }
      }
  - product: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "description": "A single Product",
         "properties": {
           "id":  { "type": "string", "required": true },
           "name":  { "type": "string", "required": true },
           "description":  { "type": "string" },
           "imageUrl":  { "type": "string" },
           "region": { "type": "string", "required": true }
         }
      }
  - products: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "description": "A collection of Products",
         "properties": {
           "size":  { "type": "integer", "required": true },
           "products":  {
              "type": "array",
              "items": { "$ref": "product" }
           }
         }
      }
resourceTypes:
  - base:
      get?:
        responses: &standardResponses
          200:
            description: OK
      put?:
        responses: *standardResponses
      patch?:
        responses: *standardResponses
      post?:
          responses:
            201:
              description: Created
      delete?:
        responses: *standardResponses
  - collection:
      type: base
      get:
        is: [ paged ]
      post:
  - typedCollection:
      type: collection
      get:
        responses:
          200:
            body:
              application/json:
                schema: <<collectionSchema>>
      post:
        body:
          application/json:
            schema: <<schema>>
        responses:
          201:
            body:
              application/json:
                schema: <<schema>>
  - member:
      type: base
      get:
      put:
      patch:
      delete:
  - typedMember:
      type: member
      get:
        responses:
          200:
            body:
              application/json:
                schema: <<schema>>
      put:
        body:
          application/json:
            schema: <<schema>>
        responses:
          200:
            body:
              application/json:
                schema: <<schema>>
      patch:
        body:
          application/json:
            schema: <<schema>>
        responses:
          200:
            body:
              application/json:
                schema: <<schema>>
      delete:
traits:
  - paged:
      displayName: paged
      queryParameters:
        start:
          displayName: start
          description: The first page to return
          type: integer
        pages:
          displayName: pages
          description: The number of pages to return
          type: integer
  - secured:
      displayName: secured
      headers:
        Authorization:
          description: The auth token for this request
      responses:
        401:
          description: Unauthorized
/presentations: &presentations
  type: { typedCollection: { schema: presentation, collectionSchema: presentations } }
  is: [ secured ]
  get:
    queryParameters:
      title:
        type: string
        displayName: title
        description: Filter by title
  /{presentationId}:
    type: { typedMember: { schema: presentation } }
    is: [ secured ]
/products:
  type: { typedCollection: { schema: product, collectionSchema: products } }
  is: [ secured ]
  get:
    queryParameters:
      region:
        type: string
        displayName: region
        description: Filter by region
  /{productId}:
    type: { typedMember: { schema: product } }
    is: [ secured ]
    /presentations: *presentations

```

**Comment by petrochenko-pavel-a** [comment]
Hm I think I know what is the possible reason let me test it.
Regards,
Pavel

**Comment by gaalandr** [comment]
Cool thank you, what is the problem?

**Comment by petrochenko-pavel-a** [comment]
I was able to reproduce and most probably fixed the issue (if the one that I reproduced is same that you faced). In my case the problem was in the fact that resource loaders was configured to trait all includes relative to RAML source path, however in most of cases we should threat them as relative to RAML file location. 

Please let me no if fix did not works for you

**Comment by ddossot** [comment]
It still doesn't work when trying a fresh build of `raml-jaxrs-maven-plugin` version `1.3.4-SNAPSHOT`

Plugin Maven config:

    <sourcePaths>
      <file>${basedir}/src/main/resources/raml/v0.1/api.raml</file>
    </sourcePaths>

RAML schema reference:

    schemas:
      - ip_hits: !include schema/ip_hits.json

Error:

<pre>
[ERROR] Failed to execute goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.4-SNAPSHOT:generate (generate-api-spec) on project raml-jaxrs-test: Error generating Java classes from: /home/ddossot/dev/projects/raml-jaxrs-test/src/main/resources/raml/v0.1/api.raml: Invalid RAML definition:
[ERROR] ERROR Include cannot be resolved /home/ddossot/dev/projects/raml-jaxrs-test/src/main/resources/raml/v0.1/schema/ip_hits.json (line 9, col 13 to 41)
</pre>

But the file indicated in the error exists:
<pre>
$ ll /home/ddossot/dev/projects/raml-jaxrs-test/src/main/resources/raml/v0.1/schema/ip_hits.json
-rw-rw-r-- 1 ddossot ddossot 253 Apr 20 11:32 /home/ddossot/dev/projects/raml-jaxrs-test/src/main/resources/raml/v0.1/schema/ip_hits.json
</pre>

**Comment by petrochenko-pavel-a** [comment]
Hi David,
I did not have time to look in it right now, but I promise to look/fix over weekend
Regards,
Pavel

**Comment by ddossot** [comment]
I've also tried with this source config for the Maven plug-in:

    <sourceDirectory>${basedir}/src/main/resources/raml/v0.1</sourceDirectory>

and the JSON schema file in the same directory as the RAML file.

With version `1.3.3` and using the following works:

    schemas:
      - ip_hits: !include ip_hits.json

But if I use a local build of `1.3.4-SNAPSHOT`, I receive:

    [ERROR] ERROR Include cannot be resolved /home/ddossot/dev/sandbox/raml-jaxrs-test/src/main/resources/raml/v0.1/ip_hits.json (line 9, col 13 to 34)

even if the file actually exists.

**Comment by petrochenko-pavel-a** [comment]
It is caused by changes in how RAML parser resolves includes.

**Comment by petrochenko-pavel-a** [comment]
added one more option for resolver, should work now, but I dislike the code there pretty much (we definitely need to drop some of options at the future)

Regards,
Pavel

**Comment by ddossot** [comment]
I'm happy to confirm that includes now work with both `sourceDirectory` and `sourcePaths` config options :+1:

**Comment by petrochenko-pavel-a** [comment]
Good to know :-)

**Comment by gaalandr** [comment]
cool thank you.
