### ISSUE TITLE
Ignore params or headers

### ISSUE THREAD

**Issue by RaphC** [mulesoft/raml-for-jax-rs#62]
Hi,

Thanks for your great plugin.

Is it possible to add a new feature. We are using your plugin to generate our Api from raml file. Some of fields and header params are only processed by filter/provider and useless on interface generated. 

So we'd like to have a plugin param (e.g : ignoredParams and ignoredHeaders) which allows to specifiy  fields name skipped by the generator.

Regards,

**Comment by petrochenko-pavel-a** [comment]
Hi RaphC looks like a pretty nice feature to add, so thanks a lot for your suggestion. I will try to find a time to work on it in nearest few days.

Regards,
Pavel

**Comment by RaphC** [comment]
Hi I've just seen that we can do similar work with GeneratorExtension (method AddParameterFilter).

**Comment by petrochenko-pavel-a** [comment]
Yep added ignoredParameters to Mojo to allow doing it without extension

**Comment by RaphC** [comment]
Thanks Pavel,

When The next version will be released ?

**Comment by petrochenko-pavel-a** [comment]
Hi RaphC, currently I plan to do release at the start of May 

Regards,
Pavel
