### ISSUE TITLE
Object naming convention generated from Nested schema

### ISSUE THREAD

**Issue by RaphC** [mulesoft/raml-for-jax-rs#63]
Hi,

The generator raml > jaxrs uses mime type and hash code to build the object name of a nested schema. Is it possible to customize the name with title properties ?

Here is the actual code for Names class
<pre><code>
    public static String buildNestedSchemaName(final MimeType mimeType)
    {
        // TODO improve naming strategy for nested schemas
        return getShortMimeType(mimeType)
               + (isBlank(mimeType.getSchema()) ? mimeType.hashCode() : mimeType.getSchema().hashCode());
    }
</code></pre>

Here is an extended one using title property field

<pre><code>
 public static String buildNestedSchemaName(final MimeType mimeType, Schema schema){
    	if(schema != null ){
    		JsonNode titleNode = schema.getContent().get("title");
    		if(titleNode != null && titleNode.isTextual()){
    			return titleNode.textValue();
    		}
    	}
    	
    	return getShortMimeType(mimeType)
                + (isBlank(mimeType.getSchema()) ? mimeType.hashCode() : mimeType.getSchema().hashCode());
</code></pre>

**Comment by petrochenko-pavel-a** [comment]
Thanks for this request. Currently there is no way to customise it. Will work on it on weekend.

Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment]
I have added useTitlePropertyForSchemaNames parameter in Mojo
Also if your generator extension implements NestedSchemaNameComputer interface you should be able to compute it from MimeType
