### ISSUE TITLE
Bad code generated from RAML header enum

### ISSUE THREAD

**Issue by ddossot** [mulesoft/raml-for-jax-rs#66]
This RAML header definition:

        Accept:
          default: application/vnd.unbounce.api.v0.1+json
          enum:
            - application/vnd.unbounce.api.v0.1+json

Generats the following enum in the resource:

    public enum Accept {

        application/vnd.unbounce.api.v0.1+json;

    }

Which can't compile.

**Comment by petrochenko-pavel-a** [comment]
I will look at weekend.

Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment]
Fixed by adding check if set of values actually can be a java enum. (I can imagine better fix but I do not see generic solution which will not be tied to specific javax.rs implementation). (Please let me know if you have an idea for generic solution)

Thanks in advance,
Pavel

**Comment by ddossot** [comment]
I don't know either, TBF.
