### ISSUE TITLE
compilation errors while trying to build the artifact

### ISSUE THREAD

**Issue by rajkumar1979** [mulesoft/raml-for-jax-rs#67]
mvn assembly:assembly -DdescriptorId=jar-with-dependencies

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project raml-jaxrs-codegen-core: Compilation failure: Compilation failure:
[ERROR] /Users/rramakrishnan/TechArchitecture/raml-for-jax-rs-master/raml-to-jaxrs/core/src/main/java/org/raml/jaxrs/codegen/core/Context.java:[504,60] cannot access com.sun.xml.bind.api.ErrorListener
[ERROR] class file for com.sun.xml.bind.api.ErrorListener not found
[ERROR] /Users/rramakrishnan/TechArchitecture/raml-for-jax-rs-master/raml-to-jaxrs/core/src/main/java/org/raml/jaxrs/codegen/core/Context.java:[508,26] cannot find symbol
[ERROR] symbol  : method info(org.xml.sax.SAXParseException)
[ERROR] location: class java.lang.Object
[ERROR] /Users/rramakrishnan/TechArchitecture/raml-for-jax-rs-master/raml-to-jaxrs/core/src/main/java/org/raml/jaxrs/codegen/core/Context.java:[505,13] method does not override or implement a method from a supertype
[ERROR] /Users/rramakrishnan/TechArchitecture/raml-for-jax-rs-master/raml-to-jaxrs/core/src/main/java/org/raml/jaxrs/codegen/core/Context.java:[514,26] cannot find symbol
[ERROR] symbol  : method warning(org.xml.sax.SAXParseException)
[ERROR] location: class java.lang.Object
[ERROR] /Users/rramakrishnan/TechArchitecture/raml-for-jax-rs-master/raml-to-jaxrs/core/src/main/java/org/raml/jaxrs/codegen/core/Context.java:[511,13] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by petrochenko-pavel-a** [comment]
This looks pretty strange. May you please provide more details about your environment.

Thanks in advance,
Pavel

**Comment by rajkumar1979** [comment]
my java version is 
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)


Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 05:51:28-0800)


I am running on Mac OSX 10.9.5

**Comment by rajkumar1979** [comment]
Are you able to build this and run it at your end, I have a raml file and I want to generate resource classes and the POJO objects from this API.

**Comment by ddossot** [comment]
In that case just use the version of the plug-in that is released in Maven
Central. No need to build it yourself.

**Comment by rajkumar1979** [comment]
I tried to build the core raml to jaxrs

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project raml-jaxrs-codegen-core: Compilation failure: Compilation failure:
[ERROR] /Users/rramakrishnan/raml/raml-for-jax-rs/raml-to-jaxrs/core/src/main/java/org/raml/jaxrs/codegen/core/Context.java:[504,60] cannot access com.sun.xml.bind.api.ErrorListener
[ERROR] class file for com.sun.xml.bind.api.ErrorListener not found
[ERROR] /Users/rramakrishnan/raml/raml-for-jax-rs/raml-to-jaxrs/core/src/main/java/org/raml/jaxrs/codegen/core/Context.java:[508,26] cannot find symbol
[ERROR] symbol  : method info(org.xml.sax.SAXParseException)
[ERROR] location: class java.lang.Object
[ERROR] /Users/rramakrishnan/raml/raml-for-jax-rs/raml-to-jaxrs/core/src/main/java/org/raml/jaxrs/codegen/core/Context.java:[505,13] method does not override or implement a method from a supertype
[ERROR] /Users/rramakrishnan/raml/raml-for-jax-rs/raml-to-jaxrs/core/src/main/java/org/raml/jaxrs/codegen/core/Context.java:[514,26] cannot find symbol
[ERROR] symbol  : method warning(org.xml.sax.SAXParseException)
[ERROR] location: class java.lang.Object
[ERROR] /Users/rramakrishnan/raml/raml-for-jax-rs/raml-to-jaxrs/core/src/main/java/org/raml/jaxrs/codegen/core/Context.java:[511,13] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by rajkumar1979** [comment]
simple maven install does not seem to work.

**Comment by ddossot** [comment]
The current master is broken, it's a known issue: https://github.com/mulesoft/raml-for-jax-rs/issues/68

Again, if all you need to do is **use** the plugin, use version `1.3.3` that has been released and is available in Maven central.

**Comment by rajkumar1979** [comment]
Thanks, I got it to work using command line for simple raml definitions, I have a raml that references a json file and its used as a trait, but the plugin does not recognize the files included and it fails.

java.lang.IllegalArgumentException: Invalid RAML definition:
8 Sequence expected
8 Include cannot be resolved webs-common-traits.json
10 trait not defined: websheaders
	at org.raml.jaxrs.codegen.core.Generator.run(Generator.java:142)
	at org.raml.jaxrs.codegen.core.Launcher.main(Launcher.java:63)

**Comment by ddossot** [comment]
It seems that you are hitting issue #72

**Comment by rajkumar1979** [comment]
One more Question,does the plugin generates resources using jaxrs 2.0?

**Comment by ddossot** [comment]
Up to you to decide: the `jaxrsVersion` config option can either be `1.1` or `2.0`.

**Comment by rajkumar1979** [comment]
How do force the plugin to generate the POJO's based on the JAX_RS version.

the second question why do you create an interface and a class in the same file and there are static methods, can you provide some explanation.

I was not able to use the interface and the class that extends Response Wrapper, I had to create an implementation class and it works.

**Comment by ddossot** [comment]
> How do force the plugin to generate the POJO's based on the JAX_RS version.

Set the `jaxrsVersion` configuration property to the value of your choice. Example: https://github.com/mulesoft/raml-for-jax-rs/blob/v1.3.3/raml-to-jaxrs/examples/jersey-example/pom.xml#L75

> the second question why do you create an interface and a class in the same file and there are static methods, can you provide some explanation.

The generator creates an interface per top level resource, DTOs from schemas and a bunch of helper classes that ease creating JAX-RS responses.

> I was not able to use the interface and the class that extends Response Wrapper, I had to create an implementation class and it works.

You should not need to do that.

All you have to do is to implement the generated interface(s) and use the response helpers, as shown in this example: https://github.com/mulesoft/raml-for-jax-rs/blob/v1.3.3/raml-to-jaxrs/examples/jersey-example/src/main/java/org/raml/jaxrs/example/impl/PresentationResource.java

**Comment by rajkumar1979** [comment]
Everything works from command line , but it fails when I include your plugins and run maven install


[ERROR] Failed to execute goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.3:generate (default) on project webs-subscription-signup: Execution default of goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.3:generate failed: A required class was missing while executing org.raml.plugins:raml-jaxrs-maven-plugin:1.3.3:generate: org/apache/commons/beanutils/ConversionException
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.raml.plugins:raml-jaxrs-maven-plugin:1.3.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/rramakrishnan/.m2/repository/org/raml/plugins/raml-jaxrs-maven-plugin/1.3.3/raml-jaxrs-maven-plugin-1.3.3.jar
[ERROR] urls[1] = file:/Users/rramakrishnan/.m2/repository/org/raml/raml-jaxrs-codegen-core/1.3.3/raml-jaxrs-codegen-core-1.3.3.jar
[ERROR] urls[2] = file:/Users/rramakrishnan/.m2/repository/org/raml/raml-parser/0.9-SNAPSHOT/raml-parser-0.9-SNAPSHOT.jar
[ERROR] urls[3] = file:/Users/rramakrishnan/.m2/repository/org/yaml/snakeyaml/1.13/snakeyaml-1.13.jar
[ERROR] urls[4] = file:/Users/rramakrishnan/.m2/repository/commons-validator/commons-validator/1.3.1/commons-validator-1.3.1.jar
[ERROR] urls[5] = file:/Users/rramakrishnan/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
[ERROR] urls[6] = file:/Users/rramakrishnan/.m2/repository/com/github/fge/json-schema-validator/2.2.6/json-schema-validator-2.2.6.jar
[ERROR] urls[7] = file:/Users/rramakrishnan/.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar
[ERROR] urls[8] = file:/Users/rramakrishnan/.m2/repository/com/googlecode/libphonenumber/libphonenumber/6.2/libphonenumber-6.2.jar
[ERROR] urls[9] = file:/Users/rramakrishnan/.m2/repository/com/github/fge/json-schema-core/1.2.5/json-schema-core-1.2.5.jar
[ERROR] urls[10] = file:/Users/rramakrishnan/.m2/repository/com/github/fge/uri-template/0.9/uri-template-0.9.jar
[ERROR] urls[11] = file:/Users/rramakrishnan/.m2/repository/com/github/fge/msg-simple/1.1/msg-simple-1.1.jar
[ERROR] urls[12] = file:/Users/rramakrishnan/.m2/repository/com/github/fge/btf/1.2/btf-1.2.jar
[ERROR] urls[13] = file:/Users/rramakrishnan/.m2/repository/com/github/fge/jackson-coreutils/1.8/jackson-coreutils-1.8.jar
[ERROR] urls[14] = file:/Users/rramakrishnan/.m2/repository/org/mozilla/rhino/1.7R4/rhino-1.7R4.jar
[ERROR] urls[15] = file:/Users/rramakrishnan/.m2/repository/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
[ERROR] urls[16] = file:/Users/rramakrishnan/.m2/repository/com/fasterxml/jackson/module/jackson-module-jsonSchema/2.4.4/jackson-module-jsonSchema-2.4.4.jar
[ERROR] urls[17] = file:/Users/rramakrishnan/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.4.0/jackson-annotations-2.4.0.jar
[ERROR] urls[18] = file:/Users/rramakrishnan/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.4.4/jackson-core-2.4.4.jar
[ERROR] urls[19] = file:/Users/rramakrishnan/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.4.4/jackson-databind-2.4.4.jar
[ERROR] urls[20] = file:/Users/rramakrishnan/.m2/repository/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar
[ERROR] urls[21] = file:/Users/rramakrishnan/.m2/repository/javax/ws/rs/jsr311-api/1.1.1/jsr311-api-1.1.1.jar
[ERROR] urls[22] = file:/Users/rramakrishnan/.m2/repository/javax/mail/mailapi/1.4.3/mailapi-1.4.3.jar
[ERROR] urls[23] = file:/Users/rramakrishnan/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
[ERROR] urls[24] = file:/Users/rramakrishnan/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
[ERROR] urls[25] = file:/Users/rramakrishnan/.m2/repository/com/sun/codemodel/codemodel/2.6/codemodel-2.6.jar
[ERROR] urls[26] = file:/Users/rramakrishnan/.m2/repository/org/jsonschema2pojo/jsonschema2pojo-core/0.4.5/jsonschema2pojo-core-0.4.5.jar
[ERROR] urls[27] = file:/Users/rramakrishnan/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
[ERROR] urls[28] = file:/Users/rramakrishnan/.m2/repository/joda-time/joda-time/2.2/joda-time-2.2.jar
[ERROR] urls[29] = file:/Users/rramakrishnan/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.11/jackson-mapper-asl-1.9.11.jar
[ERROR] urls[30] = file:/Users/rramakrishnan/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.11/jackson-core-asl-1.9.11.jar
[ERROR] urls[31] = file:/Users/rramakrishnan/.m2/repository/org/apache/commons/commons-lang3/3.2.1/commons-lang3-3.2.1.jar
[ERROR] urls[32] = file:/Users/rramakrishnan/.m2/repository/com/google/code/findbugs/annotations/1.3.9/annotations-1.3.9.jar
[ERROR] urls[33] = file:/Users/rramakrishnan/.m2/repository/org/apache/httpcomponents/httpcore/4.3/httpcore-4.3.jar
[ERROR] urls[34] = file:/Users/rramakrishnan/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar
[ERROR] urls[35] = file:/Users/rramakrishnan/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[36] = file:/Users/rramakrishnan/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[37] = file:/Users/rramakrishnan/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar
[ERROR] urls[38] = file:/Users/rramakrishnan/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
[ERROR] urls[39] = file:/Users/rramakrishnan/.m2/repository/com/sun/xml/bind/jaxb-xjc/2.1.6/jaxb-xjc-2.1.6.jar
[ERROR] urls[40] = file:/Users/rramakrishnan/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-tools-api/3.2/maven-plugin-tools-api-3.2.jar
[ERROR] urls[41] = file:/Users/rramakrishnan/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[42] = file:/Users/rramakrishnan/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[43] = file:/Users/rramakrishnan/.m2/repository/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
[ERROR] urls[44] = file:/Users/rramakrishnan/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[45] = file:/Users/rramakrishnan/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-tools-annotations/3.2/maven-plugin-tools-annotations-3.2.jar
[ERROR] urls[46] = file:/Users/rramakrishnan/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar
[ERROR] urls[47] = file:/Users/rramakrishnan/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[48] = file:/Users/rramakrishnan/.m2/repository/asm/asm/3.3.1/asm-3.3.1.jar
[ERROR] urls[49] = file:/Users/rramakrishnan/.m2/repository/asm/asm-commons/3.3.1/asm-commons-3.3.1.jar
[ERROR] urls[50] = file:/Users/rramakrishnan/.m2/repository/asm/asm-tree/3.3.1/asm-tree-3.3.1.jar
[ERROR] urls[51] = file:/Users/rramakrishnan/.m2/repository/org/codehaus/plexus/plexus-archiver/2.1.1/plexus-archiver-2.1.1.jar
[ERROR] urls[52] = file:/Users/rramakrishnan/.m2/repository/org/codehaus/plexus/plexus-io/2.0.3/plexus-io-2.0.3.jar
[ERROR] urls[53] = file:/Users/rramakrishnan/.m2/repository/com/thoughtworks/qdox/qdox/1.12.1/qdox-1.12.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.apache.commons.beanutils.ConversionException

**Comment by ddossot** [comment]
> Everything works from command line , but it fails when I include your plugins and run maven install

I don't understand, this seems contradictory. What is does "everying" means in the "Everything works from command line"? If it works from the command line, where do you "run maven install" if not on the command line?

Can you show how you configured the `raml-jaxrs-maven-plugin`? What Maven and JDK versions do you use?

**Comment by rajkumar1979** [comment]
When I said everything works from the command line I tried generating the POJO's using the command line symantics without using maven

I tried installing the maven plugin, but had some issues.
mvn -DartifactId=raml-jaxrs-maven-plugin -DgroupId=org.raml.plugins -Dversion=1.3.3 plugin:install

**Comment by rajkumar1979** [comment]
This is what I meant by command line
java -cp [path-to-the-jar] org.raml.jaxrs.codegen.core.Launcher [options]

**Comment by ddossot** [comment]
OK, but honestly, I have no idea what your trying to achieve with this Maven command:

    mvn -DartifactId=raml-jaxrs-maven-plugin -DgroupId=org.raml.plugins -Dversion=1.3.3 plugin:install

If you want to use the `raml-jaxrs-maven-plugin` in your application should add it to your `pom.xml` as shown here: 
https://github.com/mulesoft/raml-for-jax-rs/blob/v1.3.3/raml-to-jaxrs/examples/jersey-example/pom.xml#L68-L88 (replacing `${project.version}` with `1.3.3`).

**Comment by rajkumar1979** [comment]
I was trying to use the maven command to install the plugin directly to my reposiroty.

However I tried exactly what is mentioned in your pom file.
	<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>${maven-war-plugin.version}</version>
				<configuration>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
							<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
						</manifest>
						<manifestEntries>
							<Build-Date>${maven.build.timestamp}</Build-Date>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${jdk.version}</source>
					<target>${jdk.version}</target>
				</configuration>
			</plugin>
			
			<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-source-plugin</artifactId>
					<version>2.2.1</version>
					<executions>
						<execution>
							<id>attach-sources</id>
							<goals>
								<goal>jar-no-fork</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<version>2.9.1</version>
					<executions>
						<execution>
							<id>attach-javadocs</id>
							<goals>
								<goal>jar</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
			
			
			
			<plugin>
				<groupId>org.raml.plugins</groupId>
				<artifactId>raml-jaxrs-maven-plugin</artifactId>
				<version>1.3.3</version>
				<configuration>
					<sourceDirectory>${basedir}/src/main/resources/raml</sourceDirectory>
					<basePackageName>org.raml.jaxrs.example</basePackageName>
					<jaxrsVersion>2.0</jaxrsVersion>
					<useJsr303Annotations>false</useJsr303Annotations>
					<jsonMapper>jackson2</jsonMapper>
					<removeOldOutput>true</removeOldOutput>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
						<phase>generate-sources</phase>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.2.1</version>
				<configuration>
					<mainClass>org.raml.jaxrs.example.Main</mainClass>
				</configuration>
			</plugin>
		
			
			
			
		</plugins>

**Comment by rajkumar1979** [comment]
It was an issue the plugin repository , I cleaned up my repository and it works fine now.

Thanks for all the suggestions and assistance to keep me going.

**Comment by ddossot** [comment]
@rajkumar1979 Glad it finally works :smile: Can you close this issue now?
