### ISSUE TITLE
Current master does not compile

### ISSUE THREAD

**Issue by ddossot** [mulesoft/raml-for-jax-rs#68]
With Oracle JDK 1.7:

<pre>
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Generator .......................................... SUCCESS [ 14.373 s]
[INFO] Annotation Process based version of generator ...... SUCCESS [  9.323 s]
[INFO] JAXRS to RAML transformers ......................... SUCCESS [  0.074 s]
[INFO] JAX-RS RAML Maven Plug-in .......................... SUCCESS [  5.959 s]
[INFO] RAML JAX-RS Codegen ................................ SUCCESS [  0.372 s]
[INFO] RAML JAX-RS Codegen Core ........................... SUCCESS [ 11.433 s]
[INFO] RAML JAX-RS Maven Plug-in .......................... SUCCESS [  3.230 s]
[INFO] Gradle Plugin ...................................... FAILURE [  0.044 s]
[INFO] RAML to JAXRS ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.162 s
[INFO] Finished at: 2015-04-21T08:33:15-07:00
[INFO] Final Memory: 58M/732M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fortasoft:gradle-maven-plugin:1.0.5:invoke (default) on project raml-gradle-plugin: Execution default of goal org.fortasoft:gradle-maven-plugin:1.0.5:invoke failed: A required class was missing while executing org.fortasoft:gradle-maven-plugin:1.0.5:invoke: org/slf4j/impl/NewMojoLogger
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.fortasoft:gradle-maven-plugin:1.0.5
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/ddossot/.m2/repository/org/fortasoft/gradle-maven-plugin/1.0.5/gradle-maven-plugin-1.0.5.jar
[ERROR] urls[1] = file:/home/ddossot/.m2/repository/org/gradle/gradle-tooling-api/1.6/gradle-tooling-api-1.6.jar
[ERROR] urls[2] = file:/home/ddossot/.m2/repository/org/codehaus/groovy/groovy-all/2.0.6/groovy-all-2.0.6.jar
[ERROR] urls[3] = file:/home/ddossot/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :raml-gradle-plugin
</pre>

**Comment by petrochenko-pavel-a** [comment]
Gradle compiles fine in our environment. I will look what happens with it

**Comment by petrochenko-pavel-a** [comment]
Hm, I have changed Jenkins to build against latest 1.7 JDK and it still builds fine. the version of gradle-maven-plugin is the same, so there should be some deeper configuration issue on your side. May you please share the build result with -X switch to allow me continue investigation.

Thanks in advance,
Pavel

**Comment by ddossot** [comment]
I've pulled the latest master this morning and now everything compiles fine.

**Comment by petrochenko-pavel-a** [comment]
It is very strange because actually there were no changes that might be
related to it.

**Comment by ddossot** [comment]
I guess my local Maven repo was in a bad state. It seems to happen with this project as this other issue https://github.com/mulesoft/raml-for-jax-rs/issues/67 as shown. This is maybe due to flaky transitive dependencies?
