### ISSUE TITLE
This project needs a CI build

### ISSUE THREAD

**Issue by ddossot** [mulesoft/raml-for-jax-rs#69]
- The current master does not compile (see https://github.com/mulesoft/raml-for-jax-rs/issues/68 ),
- When Gradle commented it, it generates code that don't compile ( https://github.com/mulesoft/raml-for-jax-rs/issues/66 ),
- Snapshot builds are not systematically pushed to any Maven repo.

A CI build would make the former 2 points apparent and automate the latter.

It's time for MuleSoft to take this project seriously: JAX-RS integration is essential for the success of RAML in the Java ecosystem. I'm currently struggling to find workarounds for [this fixed-but-still broken bug](https://github.com/mulesoft/raml-for-jax-rs/issues/61#issuecomment-94540075): other people evaluating the technology would not have my patience and would quickly turn their backs.

TLC needed here and now!

Thank you.

**Comment by petrochenko-pavel-a** [comment]
Hi David,
>The current master does not compile (see #68 ),
Every commit is processed by Jenkins, but of course we can not be sure that it compiles in every environment

>Snapshot builds are not systematically pushed to any Maven repo.
Jenkins also publishes snapshots to QA actually and every important fix is published to mvm

Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment]
Actually we are publishing snapshots automatically to Mules repos, I added publishing snapshots to SONATYPE right now, so you should be able to use snapshots from it too. Please let me know if you see another points for improvement.

Thanks in advance,
Pavel

**Comment by ddossot** [comment]
Cool!

Is it possible to display the current status of the CI build on the project home page? If not, does anyone gets notified when the CI build breaks?

**Comment by petrochenko-pavel-a** [comment]
yep we are getting notifications on every build to slack. (This is why i
was less or more sure that build is ok). I will get a look if i can pass
this status to github easily.
26 Апр 2015 г. 5:42 пользователь "David Dossot" <notifications@github.com>
написал:
