### ISSUE TITLE
responseContainer attribute of @ApiOperation is not supported?

### ISSUE THREAD

**Issue by gorfik** [mulesoft/raml-for-jax-rs#70]
It looks like responseContainer attribute of @ApiOperation is not used, because adding this attribute to @ApiOperation does not change anything in generated code

**Comment by gorfik** [comment]
Maybe important. I used maven plugin for generation

**Comment by petrochenko-pavel-a** [comment]
Hm I know that Konst worked on it and actually implemented it. But I do not see support for resonseContainer in the code base. I will talk with him on Monday (and most likely will resolve issue)

**Comment by KonstantinSviridov** [comment]
Hi, @gorfik 

The only question I have is what name to use for the root XML element (which is the root collection returned). 

Do you have any ideas?
Is it ok to use annotation value for it?

Regards, Konstantin.

**Comment by gorfik** [comment]
Hello Konstantin,
Sorry for late response.
Do you mean @Value annotation or value field from @ApiOperation?
First option is ok. Second does not seem to be plausible.

Best regards,
Mariusz

**Comment by KonstantinSviridov** [comment]
Hi, Mariusz

I asked just the same question in the Swagger google group: https://groups.google.com/forum/#!topic/swagger-swaggersocket/QpwiDHT1qCU
It was stated in a clear form and I received a clear answer. As a result, we refused to generate XML examples and XSD schemes for classes returned by methods with `responseContainer` attribute.

On the other hand, I've just implemented `responseContainer` support for JSON schemes and examples. We support three attribute values: `List`, `Set` and `Map`. You may also want to read a my thread about legal `responseContainer` values in the same group:
https://groups.google.com/forum/#!topic/swagger-swaggersocket/vGWn7PGI85U

Regards,
Konstantin
