### ISSUE TITLE
Differences in schemas for xml and json

### ISSUE THREAD

**Issue by gorfik** [mulesoft/raml-for-jax-rs#71]
I modifed jaxbxml-example by changing @Produces annotation to @Produces({ "application/json","application/xml" }).
testobject.xsd looks like:

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://www.example.com" xmlns:ns1="http://www.example.com2">
    
    <xs:import namespace="http://www.example.com2" schemaLocation="testobject.xsd"/>
    
    <xs:import namespace="http://www.example.com" schemaLocation="testobject.xsd"/>
    
    <xs:element name="customer" type="AA"/>
    
    <xs:complexType name="AA">
    <xs:sequence>
      <xs:element name="imageData" type="xs:base64Binary" minOccurs="0"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="sntCode" type="xs:string" minOccurs="0"/>
      <xs:element name="vdc" type="xs:string" minOccurs="0"/>
      <xs:element name="children" type="testInnerObject" maxOccurs="unbounded"/>
      <xs:element name="rpp" type="anotherNamespaceObject"/>
    </xs:sequence>
    <xs:attribute name="x" type="xs:int" use="required"/>
    <xs:attribute name="married" type="xs:boolean" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="testInnerObject">
    <xs:sequence/>
    <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    
    <xs:complexType name="anotherNamespaceObject">
    <xs:sequence>
      <xs:element name="foo" type="xs:string" minOccurs="0"/>
      <xs:element ref="ns2:bar" minOccurs="0"/>
    </xs:sequence>
    </xs:complexType>
    </xs:schema>

und testobject-jsonschema.json looks like:

    {
    "required" : true ,
    "$schema" : "http://json-schema.org/draft-03/schema" ,
    "type" : "object" ,
    "properties" : {
    "@married" : {
      "type" : "string" ,
      "required" : false
    } ,
    "@x" : {
      "type" : "string" ,
      "required" : false
    } ,
    "imagedata" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sntcode" : {
      "type" : "string" ,
      "required" : false
    } ,
    "vdc" : {
      "type" : "string" ,
      "required" : false
    } ,
    "children" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "string"
        }
      ]
    }
    }
    }

You can see that field declared as 

    @XmlElement      
    byte[]imageData;

is generated as imageData in xml schema but as imagedata in json schema. Is this correct?
Moreover example for xml looks like:

    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <testobject married="some boolean value" x="some int value">
    <imagedata>some base64 encoded binary</imagedata>
    <name>some string value</name>
    <sntcode>some string value</sntcode>
    <vdc>some string value</vdc>
    <children>some arraylist value</children>
    <children>some arraylist value</children>
    <rpp>some anothernamespaceobject value</rpp>
    </testobject>

So imagedata tag is used and not imageData. Is this correct?

**Comment by petrochenko-pavel-a** [comment]
Clearly this is the bug in the naming convention. Should be pretty easy to fix.

**Comment by gorfik** [comment]
Maybe important. I used maven plugin for generation

**Comment by petrochenko-pavel-a** [comment]
It was a core problem should be fixed now.

p.s. please let me know if it will not work for you
