### ISSUE TITLE
Wrong generation of lists

### ISSUE THREAD

**Issue by gorfik** [mulesoft/raml-for-jax-rs#74]
Code, I refer to, can be found in https://github.com/gorfik/raml-testcase
I generated with maven plugin.
I have found following problems with generated json schemas when i tried to generate xml and json schemas for objects that contain list:
* If an object contains more then one list of Strings and is passed as parameter (see DxsoJobNumberRequest class) then xsd schema is properly generated 
```
    <xs:element name="cashLedgerNames" type="xs:string" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="ledgerFolderNames" type="xs:string" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
```		
but in json schema those fields are generated as objects (array is expected)
```
    "cashledgernames" : {
    "type" : "string" ,
    "required" : false
    } ,
    "ledgerfoldernames" : {
      "type" : "string" ,
      "required" : false
    }
```
* If an object contains more then one list of Strings and is returned as result of method call (@ApiResponses annotation is used)(see DxsoJobNumber class) then xsd schema is properly generated 
```    
<xs:element name="cashLedgerNames" type="xs:string" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="ledgerFolderNames" type="xs:string" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
```
but in json schema ledgerFolderNames field is not present. cashledgernames field is properly generated (field name is wrong but i submitted another issue for this problem)
```
    "cashledgernames" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "string"
        }
      ]
    }
```
* If an object contains one list of complex objects (with fields) and is passed as parameter (see DxsoJob class) then xsd schema is properly generated
```
    <xs:element name="protocol" type="protocolEntry" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
```
plus definition for protocolEntry entity

but in json schema protocol is defined as String field
```
    "properties" : {
	"protocol" : {
      "type" : "string" ,
      "required" : false
    }
    }	
```
* If an object contains one list of complex objects (with fields) and is returned as result of method call (@ApiResponses annotation is used)(see DxsoJobResponse class) then xsd schema is properly generated 
```
    <xs:element name="protocol" type="protocolEntry" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
```
plus definition for protocolEntry entity

but in json schema protocol is defined as list (this is correct) of strings (this is not correct)
```
    "properties" : {
    "protocol" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "string"
        }
      ]
    }
    }
```
* If an object contains one list of strings and is passed as parameter (see DxsoJobWithStringList class) then xsd schema is properly generated
```
    <xs:element name="protocol" type="xs:string" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
```
but in json schema protocol is defined as String field
```
    "properties" : {
    "protocol" : {
      "type" : "string" ,
      "required" : false
    }
    }
```
* If an object contains one list of strings and is returned as result of method call (@ApiResponses annotation is used)(see DxsoJobWithStringListResponse class) then xsd and json schemas is properly generated

**Comment by petrochenko-pavel-a** [comment]
Thanks a lot  for filing this. I will try to fix it asap. I already do not have a bandwidth to do it today (to sleepy), but I promise to find a window and dig in it in nearest few days.
Regards,
Pavel
