### ISSUE TITLE
Extends schemajson2pojo generation

### ISSUE THREAD

**Issue by RaphC** [mulesoft/raml-for-jax-rs#75]
Hi,

It would be nice if we had the possibility to extend the generator by adding jsonschema2pojo customAnnotator like that : 

Declare customAnnotator at the maven plugin configuration

<pre><code>
&lt;configuration&gt;
....					&lt;customAnnotator&gt;com.bouygtel.inthd.rws.build.IhdCustomPojoAnnotator&lt;/customAnnotator&gt;
....
</code></pre>

This annotator should extend the org.jsonschema2pojo.AbstractAnnotator class

The Configuration.class should referenced the customAnnotators like this

<pre><code>
public class Configuration
{
....
	private Class<? extends Annotator> customAnnotator;

    public GenerationConfig createJsonSchemaGenerationConfig()
    {
        return new DefaultGenerationConfig()
        {
....
			@Override
			public Class<? extends Annotator> getCustomAnnotator() {
				return customAnnotator;
			}
        };
    }
...

	public Class<? extends Annotator> getCustomAnnotator() {
		return customAnnotator;
	}

	public void setCustomAnnotator(Class<? extends Annotator> customAnnotator) {
		this.customAnnotator = customAnnotator;
	}

</code></pre>

This annotator would be injected by the Mojo Raml2JaxrsCodegenMojo with

<pre><code>
if(StringUtils.isNotEmpty(customAnnotator)){
                configuration.setCustomAnnotator((Class<? extends Annotator>)Class.forName(customAnnotator));
            }
</code></pre>

Then the Context.class constructor will replaced the following instruction

<pre><code>
        // configure the JSON -> POJO generator
        final GenerationConfig jsonSchemaGenerationConfig = configuration.createJsonSchemaGenerationConfig();
        schemaMapper = new SchemaMapper(new RuleFactory(jsonSchemaGenerationConfig,
            new AnnotatorFactory().getAnnotator(configuration.getJsonMapper()),
            new SchemaStore()), new SchemaGenerator());
</code></pre>

By this one 
<pre><code>
        // configure the JSON -> POJO generator
        final GenerationConfig jsonSchemaGenerationConfig = configuration.createJsonSchemaGenerationConfig();
        schemaMapper = new SchemaMapper(new RuleFactory(jsonSchemaGenerationConfig, getAnnotator(jsonSchemaGenerationConfig),
        		schemaStore), new SchemaGenerator());
</code>/pre>

Which will use the private method getAnnotator

<pre><code>
	/**
	 * 
	 * @param config
	 * @return
	 */
    private static Annotator getAnnotator(GenerationConfig config) {
        Annotator coreAnnotator = new AnnotatorFactory().getAnnotator(config.getAnnotationStyle());
        if(config.getCustomAnnotator() != null){
            Annotator customAnnotator = new AnnotatorFactory().getAnnotator(config.getCustomAnnotator());
            return new CompositeAnnotator(coreAnnotator, customAnnotator);
        }
        return coreAnnotator;
    }
</code></pre>

**Comment by petrochenko-pavel-a** [comment]
Hi thanks for very detailed proposal, I added the code following your scenario and updated the doc, please let me know if you see any points for improvement.

Regards,
Pavle

**Comment by RaphC** [comment]
Thanks Pavel for your work,

**Comment by RaphC** [comment]
Hi Pavel,

When did you schedule the next release 1.3.4 ?

Regards,
