### ISSUE TITLE
jaxrs-raml-maven-plugin should not have the kepler p2 repository in its pom hierarchy

### ISSUE THREAD

**Issue by bakito** [mulesoft/raml-for-jax-rs#84]
Currently the jaxrs-raml-maven-plugin inherits a kepler p2 repository from the jaxrs-to-raml pom
Since the maven plugin does not need any tycho all dependencies to tycho and p2 repos should be moved into tycho/p2 needing modules

**Comment by 0x3333** [comment]
+1

**Comment by mp2526** [comment]
+1

**Comment by chrisphelps** [comment]
+1, just hit this.  Any workarounds in the meantime?

**Comment by davidkarlsen** [comment]
+1

**Comment by KonstantinSviridov** [comment]
The Idea was to make the main plugin build to initiate eclipse plugin build. Right now I do not have a clean vision of what's going on. So I've removed the dependency for now.

**Comment by ShijunK** [comment]
any plan to have a bug fixing release? the latest release version 1.3.3 is complete broken due to this issue.

**Comment by philipprawe** [comment]
Checked out the actual version an hour ago and it is still broken. Had a look at the pom and tyco stuff is still commented out.
