### ISSUE TITLE
2 boolean property generate 2 different, wrong json schema entries

### ISSUE THREAD

**Issue by ymajoros** [mulesoft/raml-for-jax-rs#87]
Hello,

Some jax-ws resource returns an object, which has (among others) 2 boolean properties ("blabla" and "yo").

I'm getting this json schema:

//...
  "type" : "object" ,
  "properties" : {
    "blabla" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "string"
        }
      ]
    } ,
    "yo" : {
      "type" : "string" ,
      "required" : false
    } ,
//...

I guess both are wrong, and I should get "boolean" as type, arguably also "required": true.

My class is annotated with @XmlRootElement and @XmlAccessorType(XmlAccessType.FIELD)

I tried with the latest 1.3.4-SNAPSHOT.

xsd are correctly generated:

      <xs:element name="blabla" type="xs:boolean"/>
      <xs:element name="yo" type="xs:boolean"/>

**Comment by ddossot** [comment]
Does this happen with some JAX-RS resources only or with any that returns objects with boolean fields?

**Comment by ymajoros** [comment]
I tried a few settings, and it seemd 'consistent'.

This seems to be a regression in 1.3.4-SNAPSHOT. I'm getting strings for both in 1.3.3, which is better in my opinion.

**Comment by KonstantinSviridov** [comment]
Hi, @ymajoros 

Please, check it now for 1.3.4-SNAPSHOT. It should be fine.

Regards,  Konstantin
