### ISSUE TITLE
Access denied to: http://dl.dropbox.com/u/326301/repository/jlibs/jlibs-xml

### ISSUE THREAD

**Issue by dkirrane** [mulesoft/raml-for-jax-rs#89]
I'm hitting the following issue with Maven plugin `org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3` `generate-raml` goal

```
Failed to execute goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3:generate-raml (raml) on project my-war: 
Execution raml of goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3:generate-raml failed: 
Plugin org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3 or one of its dependencies could not be resolved: 
Failed to collect dependencies for org.raml.plugins:jaxrs-raml-maven-plugin:jar:1.3.3 (): 
Failed to read artifact descriptor for jlibs:jlibs-xml:jar:1.0: 
Could not transfer artifact jlibs:jlibs-xml:pom:1.0 from/to jlibs-repository (http://dl.dropbox.com/u/326301/repository): 
Access denied to: http://dl.dropbox.com/u/326301/repository/jlibs/jlibs-xml/1.0/jlibs-xml-1.0.pom , ReasonPhrase:Forbidden
```

**Comment by ddossot** [comment]
I can't find this repository anywhere in the project: https://github.com/mulesoft/raml-for-jax-rs/search?utf8=%E2%9C%93&q=dropbox

Is it a repository you have in your Maven settings file?

**Comment by dkirrane** [comment]
Nope I guess raml or the raml maven plugin uses JLibs
https://code.google.com/p/jlibs/
And the JLibs Maven repo is on dl.dropbox.com.

Unfortunately, dropbox domain is blocked by our corporate firewall.
I just saw this ticket to put jlibs up on Sonatype but doesn't look like it has been uploaded.
https://code.google.com/p/jlibs/issues/detail?id=52

**Comment by ddossot** [comment]
It's weird. `mvn dependency:tree | grep jlibs` finds no match so jlibs doesn't seem to be a dependency of this project.

Can you please run `mvn dependency:tree` on your side and what brings `jlibs` in?

**Comment by dkirrane** [comment]
Nothing appeared for jlibs in dep tree for my project.

I tried deleted my local maven repo & created a simple project with just the raml plugin and get a slightly different issue:

```
Failed to execute goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3:generate-raml (raml) on project mavenproject3: Execution raml of goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3:generate-raml failed: Plugin org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3 or one of its dependencies could not be resolved: Failed to collect dependencies for org.raml.plugins:jaxrs-raml-maven-plugin:jar:1.3.3 (): Failed to read artifact descriptor for jlibs:jlibs-xml:jar:1.0: Could not transfer artifact jlibs:jlibs-xml:pom:1.0 from/to kepler (http://download.eclipse.org/releases/kepler): No connector available to access repository kepler (http://download.eclipse.org/releases/kepler) of type p2 using the available factories WagonRepositoryConnectorFactory -> [Help 1]
```

My pom
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.foobar</groupId>
    <artifactId>mavenproject</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>    
    <build>
        <plugins>
            <plugin>
                <groupId>org.raml.plugins</groupId>
                <artifactId>jaxrs-raml-maven-plugin</artifactId>
                <version>1.3.3</version>
                <executions>
                    <execution>
                        <id>raml</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>generate-raml</goal>
                        </goals>
                        <configuration>
                            <title>API</title>
                            <version>1</version>
                            <baseUrl>http://localhost:8080/api</baseUrl>
                            <removeOldOutput>false</removeOldOutput>
                            <sourcePaths>
                               <!--<sourcePath>${basedir}/src/main/java/com/foorbar/Foo.java</sourcePath>-->
                            </sourcePaths>
                            <outputFile>${basedir}/src/main/webapp/docs/raml/wa-api.raml</outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by ddossot** [comment]
Now you are hitting issue #84 , which clearly needs to be fixed ASAP.

**Comment by philipprawe** [comment]
At least when I execute a  mvn dependency:tree | grep jlibs on the jaxrs-raml-maven-plugin I get something:
mvn dependency:tree | grep jlibs
Downloading: http://dl.dropbox.com/u/326301/repository/jlibs/jlibs-xml/1.0/jlibs-xml-1.0.pom
Jul 29, 2015 9:36:25 AM org.apache.maven.wagon.providers.http.httpclient.client.protocol.ResponseProcessCookies processCookies
Warnung: Cookie rejected: "[version: 0][name: flash][value: ][domain: dropbox.com][path: /][expiry: Wed Jul 29 09:36:25 CEST 2015]". Illegal domain attribute "dropbox.com". Domain of origin: "dl.dropboxusercontent.com"
Jul 29, 2015 9:36:25 AM org.apache.maven.wagon.providers.http.httpclient.client.protocol.ResponseProcessCookies processCookies
Warnung: Cookie rejected: "[version: 0][name: bang][value: ][domain: dropbox.com][path: /][expiry: Wed Jul 29 09:36:25 CEST 2015]". Illegal domain attribute "dropbox.com". Domain of origin: "dl.dropboxusercontent.com"
[ERROR] Failed to execute goal on project jaxrs-raml-maven-plugin: Could not resolve dependencies for project org.raml.plugins:jaxrs-raml-maven-plugin:maven-plugin:1.3.4-SNAPSHOT: Failed to collect dependencies for [org.apache.maven.plugin-tools:maven-plugin-tools-api:jar:3.2 (compile), org.apache.maven.plugin-tools:maven-plugin-tools-annotations:jar:3.2 (compile), fr.inria.gforge.spoon:spoon-core:jar:4.0.0 (compile), org.raml:com.mulesoft.jaxrs.raml.generator:jar:[1.0.0,) (compile)]: Failed to read artifact descriptor for jlibs:jlibs-xml:jar:1.0: Could not transfer artifact jlibs:jlibs-xml:pom:1.0 from/to jlibs-repository (http://dl.dropbox.com/u/326301/repository): peer not authenticated -> [Help 1]

I also tried to open the URL (https://dl.dropboxusercontent.com/u/326301/repository) in a browser and get a 404.
