### ISSUE TITLE
Support for type: date?

### ISSUE THREAD

**Issue by giraone** [mulesoft/raml-for-jax-rs#90]
I am wondering whether "type" : "date" is supported - it is a valid type in the RAML spec. I get the following error for my RAML file (using -jaxrsVersion "2.0"):
```
java.lang.IllegalArgumentException: Invalid RAML definition:
        ERROR invalid JSON schema (employeeDetails):
error: "date" is not a valid primitive type (valid values are: [array, boolean, integer, null, number, object, string])
    level: "error"
    domain: "syntax"
    schema: {"loadingURI":"#","pointer":"/properties/employeeSince"}
    keyword: "type"
    found: "date"
    valid: ["array","boolean","integer","null","number","object","string"]
```
The type "null" seams to be also a bit strange in the list of valid types!

**Comment by giraone** [comment]
OK. I found my problem. It guess it must be ```"type":"string", "format":"date-time"``` within a schema, the type "date" is for parameters only. Am I right?

**Comment by ddossot** [comment]
Correct.

**Comment by petrochenko-pavel-a** [comment]
Closing for now , please let me know if you see any options for improvement on our side.

Regards,
Pavel

**Comment by giraone** [comment]
Hi Pavel,

the easiest way to help others on the same issue would be to include a Date field in the included sample and show, how it is handled. 

Hans



<div>-------- Ursprüngliche Nachricht --------</div><div>Von: petrochenko-pavel-a <notifications@github.com> </div><div>Datum:08.06.2015  13:46  (GMT+01:00) </div><div>An: mulesoft/raml-for-jax-rs <raml-for-jax-rs@noreply.github.com> </div><div>Cc: giraone <hans.schuell@giraone.com> </div><div>Betreff: Re: [raml-for-jax-rs] Support for type: date? (#90) </div><div>
</div>Closing for now , please let me know if you see any options for improvement on our side.

Regards,
Pavel
