### ISSUE TITLE
resources not being found by JAX-RS 2 servlet when deployed

### ISSUE THREAD

**Issue by justjacksonn** [mulesoft/raml-for-jax-rs#95]
The generated resource interfaces that contain the @Path and methods with @POST, etc.. I then implement those classes with my resource implementations. However, when I deploy the app, the annotations seemed to be ignored. I am specifically using an @ApplicationPath() configuration java class file, which I then include the packages of my implementation resource that implements the generated interface.  When I include the package of the generated interface resource class, it DOES find the annotations and registers.. but when the request is made to the service it looks to try to create the interface class, not the implementation class... obviously not going to work.

How do we get implementation classes without the annotations in them like @Path, etc to register with the JAX-RS servlet? I am using Jersey 2.x presently in a Jetty 9.x container.

**Comment by justjacksonn** [comment]
To add to this.. did a bit more looking into this... when using the @ApplicationPath annotation, and I specify JUST the package to my implementation class, it seems to discover the same resource twice rather than recognizing that my class implements an interface where the path annotation exists. If I specify JUST the generated interface package, it finds the resource, but then at runtime fails to create the class..which of course make sense as well. If I specify the common base package name (in the @packages() in my class with @ApplicationPath in it), it again finds the resources twice. So it seems thus far, there isn't any way to implement the generated annotated interface with JAX-RS 2. The error is this:

```
WARNING: A resource model has ambiguous (sub-)resource method for HTTP method POST and input mime-types as defined by"@Consumes" and "@Produces" annotations at Java methods public com.company.generated.resource.TestManagementResource$PostTestResponse com.company.rest.TestManagement.postTest(com.company.generated.model.Test) throws java.lang.Exception and public abstract com.company.generated.resource.TestManagementResource$PostTestResponse com.company.generated.resource.TestManagementResource.postTest(com.company.generated.model.Test) throws java.lang.Exception at matching regular expression /service. These two methods produces and consumes exactly the same mime-types and therefore their invocation as a resource methods will always fail.
```

**Comment by ddossot** [comment]
I might be misguided, but isn't this a question more appropriate for the Jersey user group?

**Comment by justjacksonn** [comment]
I don't think this would fit Jersey, as it seems to be the way raml-jaxrs is building interfaces and that classes extending those interfaces are not being registered within JAX-RS at runtime. Hmm..maybe it is specific to that..but it makes me wonder if the raml-jaxrs folks tried anything like this. I would assume if they had, they'd notice that their generated interfaces being extended by classes without JAX-RS annotations were not being discovered at runtime and thus their tool is not going to work. So while I think it *might* be a runtime JAX-RS/Jersey issue, the raml-jaxrs team at the least should be aware of it and either change/add code to ensure it works, or possibly indicate that the annotations should be added to the implemented code as well.

As an update, after figuring out I was missing some jackson/jaxrs libraries, I am still seeing the same issue in that I still have to add the JAX-RS annotations to my implementation class for the paths/methods to register and work with requests.

I will still say that perhaps I am missing something, but nothing that has been read in any of the documents have given me a solution or told me I am doing something wrong thus far. I'd be happy to see it work as designed though. I think it's a pretty decent way building server side JAX-RS from RAML and JSon Schema.

**Comment by ddossot** [comment]
I'm using the RAML to JAX-RS generator with one Java/CXF/JAX-RS2 project and with one Scala/Jersey2/JAX-RS2 project. I don't put any of my implementation classes in the same packages than the generated code and have none of the problems you're reporting here.

But I may as well have been very lucky so far :stuck_out_tongue_closed_eyes:

**Comment by justjacksonn** [comment]
Hmm.. ok.. little more to add to this.. turns out that I implement my interface that is generated.. if I do NOT provide the @Path() within my implementation class, nothing works. When I DO provide it, all works. I don't have to put the @POST, @GET etc around methods..the overridden methods work as is. So again, I hope it's just something I missed and the lack of docs explaining how to use it in a JAX-RS 2/Servlet 3.x container like Jetty.

At least it's only one @Path per resource class at this point.. not a big deal to provide.

**Comment by justjacksonn** [comment]
@ddossot I should add I do NOT put my implementation classes in the same packages either.. the most obvious reason being the generated packaged gets blown away on a "clean" build. :).

**Comment by ddossot** [comment]
You actually could put them in the same package, as long as you do not put them in the same source folders they would not be blown away by a clean build/

**Comment by ddossot** [comment]
You should not need to put any annotation on your implementation class: they should be inherited from the interface.

Using Jersey `2.12` and the Jetty container provided in `jersey-container-jetty-servlet`, I don't need to add any JAX-RS annotation on my implementation classes: I have no idea why this doesn't work for you :cry:

**Comment by justjacksonn** [comment]
Ok.. so something to figure out then. I am building the .war file and deploying in a running container with hot-swap. Doubt that would be the reason though. It's probably a configuration issue.. like I said I am not using web.xml or anything so must need to add/modify something within the class configuration for it to use/see the interface annotation.

**Comment by KonstantinSviridov** [comment]
Hi, @justjacksonn 

I'm closing it for now because the issue does not seem to be related with the generator. Please let me know if you find some generator malfunction.

Thanks in advance.
Konstantin.
