### ISSUE TITLE
Generated code is not compiling

### ISSUE THREAD

**Issue by andrespires** [mulesoft/raml-for-jax-rs#96]
Hi, 

I am generating the source code using a simple RAML and the resource code is not compiling. 

Error message: 
> Error:(26, 5) java: com.acme.api.resource.Hello.GetHelloResponse is not abstract and does not override abstract method getHeaderString(java.lang.String) in javax.ws.rs.core.Response

Here is the code generated

```java

@Path("hello")
public interface Hello {
    /**
     * 
     */
    @GET
    @Produces({
        "application/json"
    })
    Hello.GetHelloResponse getHello()
        throws Exception
    ;

    class GetHelloResponse extends ResponseWrapper
    {


        private GetHelloResponse(Response delegate) {
            super(delegate);
        }

        /**
         * 
         * @param entity
         *     
         */
        public static Hello.GetHelloResponse withJsonOK(Json1027969548 entity) {
            Response.ResponseBuilder responseBuilder = Response.status(200).header("Content-Type", "application/json");
            responseBuilder.entity(entity);
            return new Hello.GetHelloResponse(responseBuilder.build());
        }

    }
}

```

I am using Spring boot with *spring-boot-starter-jersey* dependency, which in turn uses the *javax.ws.rs:javax.ws.rs-api:2.0.1* library. Any idea what's going on?

**Comment by justjacksonn** [comment]
I have an idea.. given that I just came across this same situation. But I am not sure it is the same as what you are seeing as I am not using Spring. Anyway, there is an option that you need to pass to the raml-jaxrs generator. My arguments:

			<arg value="-jaxrsVersion"/>
			<arg value="2.0"/>

See if that helps.. although this is for an ant script, however you are calling the tool be it CLI or maven or what not, pass that argument with 2.0 and see what happens.

**Comment by ddossot** [comment]
I agree: it seems the generator is configured to target JAX-RS 1.1 when it should be configured for 2.0.

**Comment by justjacksonn** [comment]
By default it is 1.1, I read that in the doc somewhere. You do have to specify 2.0. Did you try that and it worked for you? That did fix one issue I was having, especially because I was using 2.x libraries.

**Comment by andrespires** [comment]
That was it, thanks.
